### ISSUE TITLE
Update Part2Step17 with latest requirements & dataRepo changes 

### ISSUE THREAD

**Issue by mmschaefer** [SolidDesignNet/j1939-84#143]
Update Part02Step17Controller.java & Part02Step17ControllerTest.java to comply with the latest requirements and full coverage on unit testing.

**Comment by mmschaefer** [comment]
Task 3, 4 & 5 #11-23 of Joe's notes

**Comment by battjt** [comment]
Updates 1-6 to be finished this week.
