### ISSUE TITLE
Excess Text in Tests 1.9 and 2.7

### ISSUE THREAD

**Issue by battjt** [SolidDesignNet/j1939-84#171]
From j1939-84 created by [ericthomasswenson](https://github.com/ericthomasswenson): Equipment-and-Tool-Institute/j1939-84#1164  

Excess Text in Tests 6.1.9 and 6.2.7

Start Test 1.9 - Component ID: Make
14:51:44.9738 Destination Specific **_org.etools.j1939tools.j1939.packets._**ComponentIdentification**_Packet_** Request to Engine #1 (0)
14:51:44.9782 18EA00F9 [3] EB FE 00 (TX)
14:51:45.1418 1CFEEB00 [49] 49 4E 54 20 20 2A 37 35 37 31 32 34 32 30 32 31 2A 58 58 58 58 58 58 58 58 58 58 58 58 58 58 2A 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 2A
Component Identification from Engine #1 (0): {

Start Test 2.6 - DM56: Model year and certification engine family
14:53:46.0076 Destination Specific DM56 Request to Engine #1 (0)
14:53:46.0100 18EA00F9 [3] C7 FC 00 (TX)
14:53:46.0165 18E8FF00 [8] 01 FF FF FF F9 C7 FC 00

14:53:46.0195 Destination Specific 
**_org.etools.j1939tools.j1939.packets._**ComponentIdentification**_Packet_** Request to Engine #1 (0)
14:53:46.0220 18EA00F9 [3] EB FE 00 (TX)
14:53:46.1807 1CFEEB00 [49] 49 4E 54 20 20 2A 37 35 37 31 32 34 32 30 32 31 2A 58 58 58 58 58 58 58 58 58 58 58 58 58 58 2A 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 2A
Component Identification from Engine #1 (0): {
  Make: INT
  Model: 7571242021
  Serial: XXXXXXXXXXXXXX
  Unit: 0000000000000000

**Comment by mmschaefer** [comment]
Previously fixed:
<img width="868" alt="Screen Shot 2022-08-03 at 12 10 51 PM" src="https://user-images.githubusercontent.com/7682306/182657407-af66addd-e8e5-4a62-b6ff-a436d3d972c7.png">
<img width="788" alt="Screen Shot 2022-08-03 at 12 10 20 PM" src="https://user-images.githubusercontent.com/7682306/182657410-7dfbc1c3-2114-4660-9c42-5435b741baf6.png">
