### ISSUE TITLE
Error message for 6.1.4.2.e should say FAIL:

### ISSUE THREAD

**Issue by battjt** [SolidDesignNet/j1939-84#172]
From j1939-84 created by [ericthomasswenson](https://github.com/ericthomasswenson): Equipment-and-Tool-Institute/j1939-84#1162  

Error message for 6.1.4.2.e should say FAIL: 

  D       1  SPN 7353 - Engine Exhaust 1 Corrected Nox
  D   T   1  SPN 7393 - AFT 1 Particulate Sensor Current
  D       2  SPN 12750 - AFT 1 SCR 1 Engine Exhaust NOx Mass Flow
  D       2  SPN 12751 - AFT 1 SCR 1 Tailpipe NOx Mass Flow
]

FAIL: 6.1.4.2.d - SP 12675 is not included in DM24 response from Engine #1 (0)
/* NOx Tracking Engine Activity Lifetime Fuel Consumption Bins (64258)
**_WARN_**: 6.1.4.2.e - SP 12730 is not included in DM24 response from Engine #1 (0)
/* GHG Tracking Lifetime Engine Run Time (64252)
WARN: 6.1.4.2.f - SP 12691 is not included in DM24 response from Engine #1 (0)
/* GHG Tracking Lifetime Active Technology Index (64257)

**Comment by mmschaefer** [comment]
Previously fixed:
<img width="848" alt="Screen Shot 2022-08-03 at 12 01 41 PM" src="https://user-images.githubusercontent.com/7682306/182657601-243df8c2-3fe0-48ed-96d1-2192a659c3e0.png">
